language: node_js
node_js:
- iojs-v1
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:
  - secure: O77r+fFoaapmAwOuvAI4KANZc1LEW+WNJSazGVwUGSYcogyTWnGt++Hp+/i+90ujJL7K8DAVzIGuSWWqDdVao7Idx4vhD9vxL5rtMjUG7QAEmj7P7clXEONR/zSl7aHMtUk92eoT4lIptOcYCIDIOZ/Dhe5TkGw8y7Gvhd8J0Fs=
deploy:
  provider: npm
  email: david@excellenteasy.com
  skip_cleanup: true
  api_key:
    secure: VrAcjao6P3xdrcUXCcMZQx6G+bdO8v6BiQJ5Lr9b1o9fV5zSKADTM0IgoJz1lmvhE2ZdEABYvZqgn+9Fy9LV3GyXS/Qvj7GSUu35wCkDFvScNGJ7tZKgN8CFhAaXkmNOz5XlHsF5jaWgtPChejVhIFMmJD26AhoNRY//e1vSSvc=
  on:
    branch: master
    repo: "excellenteasy/react-component"
